/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookRouteImport } from './routes/book'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AppointmentNewRouteImport } from './routes/appointment.new'
import { Route as AppointmentSavedRouteImport } from './routes/appointment.saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentNewRoute = AppointmentNewRouteImport.update({
  id: '/appointment/new',
  path: '/appointment/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentSavedRoute = AppointmentSavedRouteImport.update({
  id: '/appointment/saved',
  path: '/appointment/saved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/clients': typeof ClientsRoute
  '/settings': typeof SettingsRoute
  '/appointment/new': typeof AppointmentNewRoute
  '/appointment/saved': typeof AppointmentSavedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/clients': typeof ClientsRoute
  '/settings': typeof SettingsRoute
  '/appointment/new': typeof AppointmentNewRoute
  '/appointment/saved': typeof AppointmentSavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/clients': typeof ClientsRoute
  '/settings': typeof SettingsRoute
  '/appointment/new': typeof AppointmentNewRoute
  '/appointment/saved': typeof AppointmentSavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/clients'
    | '/settings'
    | '/appointment/new'
    | '/appointment/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/clients'
    | '/settings'
    | '/appointment/new'
    | '/appointment/saved'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/clients'
    | '/settings'
    | '/appointment/new'
    | '/appointment/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  ClientsRoute: typeof ClientsRoute
  SettingsRoute: typeof SettingsRoute
  AppointmentNewRoute: typeof AppointmentNewRoute
  AppointmentSavedRoute: typeof AppointmentSavedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment/new': {
      id: '/appointment/new'
      path: '/appointment/new'
      fullPath: '/appointment/new'
      preLoaderRoute: typeof AppointmentNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment/saved': {
      id: '/appointment/saved'
      path: '/appointment/saved'
      fullPath: '/appointment/saved'
      preLoaderRoute: typeof AppointmentSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  ClientsRoute: ClientsRoute,
  SettingsRoute: SettingsRoute,
  AppointmentNewRoute: AppointmentNewRoute,
  AppointmentSavedRoute: AppointmentSavedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
