/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderRouteImport } from './routes/_provider'
import { Route as ImportRouteImport } from './routes/import'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProviderBookRouteImport } from './routes/_provider.book'
import { Route as ProviderClientsRouteImport } from './routes/_provider.clients'
import { Route as ProviderAppointmentNewRouteImport } from './routes/_provider.appointment.new'
import { Route as ProviderAppointmentSavedRouteImport } from './routes/_provider.appointment.saved'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/_provider',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderBookRoute = ProviderBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderClientsRoute = ProviderClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderAppointmentNewRoute = ProviderAppointmentNewRouteImport.update({
  id: '/appointment/new',
  path: '/appointment/new',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderAppointmentSavedRoute =
  ProviderAppointmentSavedRouteImport.update({
    id: '/appointment/saved',
    path: '/appointment/saved',
    getParentRoute: () => ProviderRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/book': typeof ProviderBookRoute
  '/clients': typeof ProviderClientsRoute
  '/appointment/new': typeof ProviderAppointmentNewRoute
  '/appointment/saved': typeof ProviderAppointmentSavedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/book': typeof ProviderBookRoute
  '/clients': typeof ProviderClientsRoute
  '/appointment/new': typeof ProviderAppointmentNewRoute
  '/appointment/saved': typeof ProviderAppointmentSavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_provider': typeof ProviderRouteWithChildren
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/_provider/book': typeof ProviderBookRoute
  '/_provider/clients': typeof ProviderClientsRoute
  '/_provider/appointment/new': typeof ProviderAppointmentNewRoute
  '/_provider/appointment/saved': typeof ProviderAppointmentSavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import'
    | '/settings'
    | '/book'
    | '/clients'
    | '/appointment/new'
    | '/appointment/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import'
    | '/settings'
    | '/book'
    | '/clients'
    | '/appointment/new'
    | '/appointment/saved'
  id:
    | '__root__'
    | '/'
    | '/_provider'
    | '/import'
    | '/settings'
    | '/_provider/book'
    | '/_provider/clients'
    | '/_provider/appointment/new'
    | '/_provider/appointment/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProviderRoute: typeof ProviderRouteWithChildren
  ImportRoute: typeof ImportRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_provider': {
      id: '/_provider'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_provider/book': {
      id: '/_provider/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof ProviderBookRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/_provider/clients': {
      id: '/_provider/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ProviderClientsRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/_provider/appointment/new': {
      id: '/_provider/appointment/new'
      path: '/appointment/new'
      fullPath: '/appointment/new'
      preLoaderRoute: typeof ProviderAppointmentNewRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/_provider/appointment/saved': {
      id: '/_provider/appointment/saved'
      path: '/appointment/saved'
      fullPath: '/appointment/saved'
      preLoaderRoute: typeof ProviderAppointmentSavedRouteImport
      parentRoute: typeof ProviderRoute
    }
  }
}

interface ProviderRouteChildren {
  ProviderBookRoute: typeof ProviderBookRoute
  ProviderClientsRoute: typeof ProviderClientsRoute
  ProviderAppointmentNewRoute: typeof ProviderAppointmentNewRoute
  ProviderAppointmentSavedRoute: typeof ProviderAppointmentSavedRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderBookRoute: ProviderBookRoute,
  ProviderClientsRoute: ProviderClientsRoute,
  ProviderAppointmentNewRoute: ProviderAppointmentNewRoute,
  ProviderAppointmentSavedRoute: ProviderAppointmentSavedRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProviderRoute: ProviderRouteWithChildren,
  ImportRoute: ImportRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
